package main

import (
	"socketChat/cmd/app"
	_"socketChat/docs" // docs is generated by Swag CLI, you have to import it.
)


//	@title			Socket Chat API Documentation
//	@version		1.0
//	@description	A web socket based chat application.
//	@termsOfService	https://github.com/rizasghari

//	@contact.name	Riza Asghari
//	@contact.url	https://github.com/rizasghari
//	@contact.email	developer.rizasghari@gmail.com

//	@license.name	Apache 2.0
//	@license.url	http://www.apache.org/licenses/LICENSE-2.0.html

//	@host		localhost:8080
//	@BasePath	/api/v1

//	@securityDefinitions.basic	JWT
//	@in							header
//	@name						Authorization

//	@externalDocs.description	Github
//	@externalDocs.url			https://github.com/rizasghari

func main() {
	app.GetApp().LetsGo()
}
