[app]

[http]
port = 8080

[jwt]
expiration_time = 24

[database]
host = "socket-chat-db"
port = 5432
user = "postgres"
password = "postgres"
name = "socket_chat_db"
ssl = "disable"
timezone = "Europe/Istanbul"

[redis]
host = "chat-redis"
port = 6379
password = "ChatRedisPassword"
# Cache duration in seconds
cache = 3600

[minio]
endpoint = "socket-chat-minio:9000"
external_endpoint = "localhost:9000"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
use_ssl = false
